"""Regenerate universe.json from index constituents.

S&P 500 + S&P/ASX 200, read from Wikipedia. Run this when you want to refresh the
membership; fetch.py only ever reads the resulting universe.json.

Wikipedia returns 403 to the default urllib user agent, so one is set explicitly.
"""

import io
import json
import urllib.request

import pandas as pd

UA = "Mozilla/5.0 (consensus-drift; https://charlietrenorden.com/consensus-drift/)"

# (market, url, ticker column, name column, suffix)
# Suffix is what Yahoo needs to identify the listing. Euro Stoxx is the odd one out:
# its constituents sit on several different exchanges and the Wikipedia ticker column
# already carries the right suffix (ADS.DE, MC.PA), so it is used verbatim.
#
# NOT INCLUDED: Nikkei 225. Its Wikipedia page carries no constituent table, and
# guessing 4-digit codes is not worth the false tickers. Needs a different source.
SOURCES = [
    ("US",  "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies", "Symbol", "Security", ""),
    ("ASX", "https://en.wikipedia.org/wiki/S%26P/ASX_200", "Code", "Company", ".AX"),
    ("UK",  "https://en.wikipedia.org/wiki/FTSE_100_Index", "Ticker", "Company", ".L"),
    ("EU",  "https://en.wikipedia.org/wiki/EURO_STOXX_50", "Ticker", "Name", None),
    ("CA",  "https://en.wikipedia.org/wiki/S%26P/TSX_60", "Symbol", "Company", ".TO"),
]


def grab(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8", "replace")


def main():
    names, seen = [], set()
    for market, url, code_col, name_col, suffix in SOURCES:
        tables = pd.read_html(io.StringIO(grab(url)))
        table = next(t for t in tables
                     if any(code_col in str(c) for c in t.columns) and len(t) > 30)
        added = 0
        for _, row in table.iterrows():
            code = str(row[code_col]).strip().upper()
            label = str(row[name_col]).strip()
            if not code or code == "NAN":
                continue
            if suffix is None:
                ticker = code                      # already carries its exchange
            elif market == "US":
                ticker = code.replace(".", "-")    # Yahoo wants a dash for share classes
            else:
                ticker = code.replace(".", "-") + suffix
            if ticker in seen:
                continue
            seen.add(ticker)
            names.append({"ticker": ticker, "name": label, "market": market})
            added += 1
        print(f"  {market}: {added} names")

    doc = {"_comment": "Generated by build_universe.py from S&P 500, ASX 200, FTSE 100, "
                       "EURO STOXX 50 and TSX 60. "
                       "fetch.py reads this and nothing else.",
           "names": names}
    with io.open("universe.json", "w", encoding="utf-8", newline="\n") as fh:
        fh.write(json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
    print(f"\nuniverse.json: {len(names)} names")


if __name__ == "__main__":
    main()
